services:
  - type: web
    name: wordle-backend
    env: node
    plan: free
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: <RENDER_DB_HOST>
      - key: DB_USER
        value: <RENDER_DB_USER>
      - key: DB_PASSWORD
        value: <RENDER_DB_PASSWORD>
      - key: DB_NAME
        value: palabras_db
      - key: DB_PORT
        value: 3306
